frontend:
    OIDC_CLIENT_SECRETS: ga4gh/server/client_secrets.json
    OIDC_OPENID_REALM: http://142.11.33.237:8000/oidc_callback
    OIDC_ID_TOKEN_COOKIE_SECURE: False
    OIDC_REQUIRE_VERIFIED_EMAIL: False
    SECRET_KEY: key
    TESTING: False
    DEBUG: False
server:
    INITIAL_PEERS: ga4gh/server/templates/initial_peers.txt
